/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan.admin_gudang.barang_masuk;

import Lib.BarangLib;
import Lib.BarangMasukLib;
import Lib.TransaksiLib;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import Model.BarangMasuk;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author Timy
 */



public class BarangMasukForm extends javax.swing.JFrame {

    protected BarangMasuk barangMasukModel;
    
    private static BarangMasukForm barangMasukIndexForm = null;
    
    /**
     * Creates new form BarangMasukForm
     */
    public BarangMasukForm() {
        initComponents();
        barangMasukModel = new BarangMasuk();
        fillTable();
    }
    
    public static BarangMasukForm showForm() {
        if (barangMasukIndexForm == null) {
            barangMasukIndexForm = new BarangMasukForm();
        }
        
        return barangMasukIndexForm;
    }
    
    public void fillTable() {
        try {
            Object[] column = new String[]{"id", "#", "Tanggal", "Pemasok", "Barang", "Jumlah"};

            Object[][] data = new Object[][]{
            };
            
            DefaultTableModel model = new DefaultTableModel(data, column){

                @Override
                    public boolean isCellEditable(int row, int col){
                            return false;
                    }
            };

            List<BarangMasukLib> barangMasukObject = this.barangMasukModel.getItems();
            model.setRowCount(0);
            
            if (barangMasukObject != null) {
                int index = 0;

                for (BarangMasukLib item : barangMasukObject) {
                    index++;
                    
                    List<BarangLib> itemBarangObject = item.itemDetail();
                    Optional<BarangLib> itemFirst = itemBarangObject.stream().findFirst();
                    
                    BarangLib item_name = BarangLib.NOT_FOUND;
                    
                    if (itemFirst.isPresent()) {
                        item_name = itemFirst.get();
                    }

                    Object[] rowData = new Object[] {
                       item.getId(),
                       String.valueOf(index),
                       item.getTanggal(),
                       item.getPemasok(),
                       item_name.getNama(),
                       String.valueOf(item.getQty())
                    };

                    model.addRow(rowData);
                }
            }

            this.table.setModel(model);
            this.table.getColumnModel().getColumn(0).setMinWidth(0);
            this.table.getColumnModel().getColumn(0).setMaxWidth(0);
            this.table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 390, 320));
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 390, -1));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setText("Pencarian");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel1.setText("Barang Masuk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.setPreferredSize(new java.awt.Dimension(71, 23));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(71, 23));
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        BarangMasukCreate.showForm().setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        BarangMasukForm.barangMasukIndexForm = null;
    }//GEN-LAST:event_formWindowClosing

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        final int rowIndex = table.getSelectedRow();
        
        if (rowIndex != -1) {
            final Integer id = Integer.valueOf(table.getValueAt(rowIndex, 0).toString());
        
            boolean deleteRow = this.barangMasukModel.delete(id);

            if (deleteRow) {
                this.fillTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan Proses Hapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
            return;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Data Belum Terpilih", "Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasukForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasukForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
